### ISSUE TITLE
help on 'interval' and 'distribution, and residual analysis

### ISSUE THREAD

**Issue by jermaine1ronquillo** [PYFTS/pyFTS#11]
I'd like to know how to interpret model result on 'interval' , 'distribution', and residual analysis
Regards,

**Comment by petroniocandido** [comment]
The interval forecast (generated by IFTS, PWFTS and EnsembleFTS methods) is a list where each element is a prediction interval, a tuple of two numbers where the first is the lower bound and the second is the upper bound.

The distribution forecast (generated by PWFTS and EnsembleFTS methods) is a pyFTS.probabilistic.ProbabilityDistribution object that represents an probability distribution, check the documentation on https://pyfts.github.io/pyFTS/build/html/pyFTS.probabilistic.html#module-pyFTS.probabilistic.ProbabilityDistribution

What is your doubt about the ResidualAnalysis?

**Comment by jermaine1ronquillo** [comment]
Thank you for the reply. Regarding residual analysis  I would like to know what is the use of it.
