### ISSUE TITLE
Constructor of FTS functions:

### ISSUE THREAD

**Issue by guicostas** [PYFTS/pyFTS#13]
Example:

model = chen.ConventionalFTS(partitioner=fs)

Returns the following statement:

TypeError: __init__() missing 1 required positional argument: 'name'

**Comment by petroniocandido** [comment]
What is the issue? In which context the error appear?

**Comment by guicostas** [comment]
Just edited and updated with the error information!

**Comment by petroniocandido** [comment]
You are using an very old version of pyFTS. Please update the version using the following command:

pip3 install -U git+https://github.com/PYFTS/pyFTS
