### ISSUE TITLE
Question on generators parameter

### ISSUE THREAD

**Issue by jermaine1ronquillo** [PYFTS/pyFTS#19]
Hi,

I'd like to ask how to use _generators_ parameter for multivariate forecasting. I have read your tutorial: [https://towardsdatascience.com/a-short-tutorial-on-fuzzy-time-series-part-ii-with-an-case-study-on-solar-energy-bda362ecca6d](url) and you used date as exogenous data. Specifically my question is if I have two exogenous data for example wind and temperature, what will be my generator? My question may be vague, I'm sorry. Great library, thank you for updating.

**Comment by petroniocandido** [comment]
Hi Jermaine!

Please check this issue about complex generator in MVFTS: https://github.com/PYFTS/pyFTS/issues/15#issuecomment-464767484

If you still have any questions, please don't hesitate to get in touch!
