### ISSUE TITLE
How the predict function works?

### ISSUE THREAD

**Issue by pintuiitbhi** [PYFTS/pyFTS#22]
Case 1:
`forecasts = model.predict([1020,3840,1920], steps_ahead=9)`
Where [1020,3840,1920] is the last 3 data point of time series in "train_uv"
Case 2:
`forecasts = model.predict(train_uv, steps_ahead=9)`

Both are giving different forecast i.e 9 future data points. 

How the predict function is working in these two cases above?

**Comment by petroniocandido** [comment]
In order to reproduce the problem, could you please share the code and data you used?

**Comment by pintuiitbhi** [comment]
Actually, I don't have permission to share the dataset. But you can take any erratic dataset and work on it.

According to me this is how "predict" function is working:
### Case 1: (Order =3 and model is HOFTS  | Grid partition | triangular membership| 35 partitions)
`forecasts = model.predict([1020,3840,1920], steps_ahead=9)`
The **predict** function with take _[1020,3840,1920]_ values and predict the next one. Let's say _864_. Now **predict** will use [_3840, 1920, 864]_ to predict the next values. Let it be _950_. Again **predict** will use _[1920, 864, 950]_ to predict the next value. And so on till we get _9 future data points._

### Case 2:
`forecasts = model.predict(train_uv, steps_ahead=9)`
Here **predict** will extract the _last 3 data points i.e [1020,3840,1920]_ and it will use these three values to find the next one as we did above in Case 1.

Am I right?

**Comment by petroniocandido** [comment]
On predict function, when using the steps_ahead parameter, you may also have to use the start_at parameter, in case you don't want to start forecasting at the beginning of the input data. Please also verify if your installed version of pyFTS is the most recent version.

**Comment by pintuiitbhi** [comment]
>  Please also verify if your installed version of pyFTS is the most recent version.

It is the lastest one (1.6).

What I said about "predict" function , is it correct?
https://github.com/PYFTS/pyFTS/issues/22#issuecomment-499540269

**Comment by petroniocandido** [comment]
If using start_at (not starts_at) do not change the response, probably your version is not the last, try updating it directly from the git repository.

Your understanding about the predict funciont (in case 1) is correct. But in case 2 the function will pick not the last, but the first lags of data. Please let me know in case it does not work for you.

**Comment by pintuiitbhi** [comment]
Whether I use
### Case 1:
`forecastsTest= model.predict(train_uv, start_at=144, steps_ahead=12)`
or 
### Case 2:
`forecastsTest = model.predict(train_uv, steps_ahead=12)`

Both gives the same "forecastTest".

**What does actually "start_at" do?** 

**Is the following intrepretation of "predict" function correct?**
In **case 2**, _predict_ function will pick first 3 (Suppose order of hofts is 3) data points from "train_uv" and starts predicting. Next 12 points it will predict.
In **case 1**, _predict_ will pick 3 data points starting from index 144 ie. elements at index 144, 145, 146 and starts predicting the next 12 data points.

**Comment by pintuiitbhi** [comment]
Order = 5

Output waveform of predict in 
`forecasts = model.predict(train_uv)`
this case is:
![tr](https://user-images.githubusercontent.com/29093550/59099139-e15e1700-8911-11e9-88dd-b04370db46a6.png)

Output waveform of predict in
`forecasts = model.predict(train_uv[:5],steps_ahead=139)`
this case is:
![tr2](https://user-images.githubusercontent.com/29093550/59099150-e6bb6180-8911-11e9-8199-7cd7bfc4732b.png)

> Your understanding about the predict funciont (in case 1) is correct. But in case 2 the function will pick not the last, but the first lags of data.

If `forecasts = model.predict(train_uv)` picks the first 5 lags the output of both should be same. How is prediction so perfect in this `forecasts = model.predict(train_uv)` ?

**Comment by petroniocandido** [comment]
I will try to simulate this issue on HOFTS method. However, apparently you data have seasonality (+/- at every 20 instances). Have you tried to use multivariate methods for that (MVFTS, WMVFTS, etc)  ?
