### ISSUE TITLE
forecasting algorithms

### ISSUE THREAD

**Issue by georgevarelas** [PYFTS/pyFTS#24]
Is there anywhere in the documentation more information on what algorithms does the forecasting with HighOrderFTS use?
I'd like to know more details on such things in order to iclude them in a perspective publication.

Thank you in advance
George

**Comment by petroniocandido** [comment]
Maybe you consider reading the following papers:
- https://doi.org/10.1109/FUZZ-IEEE.2017.8015732
- https://doi.org/10.3390/en11112952
There are other papers but they are in Portuguese language, and there are some others in press, but we can not reference them yet. If you want to cite pyFTS library, please reference the DOI https://doi.org/10.5281/zenodo.597359 .

Thanks for your interest!
