### ISSUE TITLE
Partitioner.fuzzyfy cannot handle parameters mode='vector' and method='maximum'

### ISSUE THREAD

**Issue by shaneing** [PYFTS/pyFTS#27]
I invoke method as follows:

```
cpu.partitioner.fuzzyfy(data_point, mode='sets', method='maximum', alpha_cut=0.0)
```

Then, the output as follows:

```
['cpu.busy0', 'cpu.busy0', 'cpu.busy1', 'cpu.busy1', 'cpu.busy1', 'cpu.busy1']
```

But, I only want their values.

**Comment by shaneing** [comment]
It is equivalent to `np.max(var.partitioner.fuzzyfy(data_point, mode='vector', method='fuzzy'))`.

**Comment by petroniocandido** [comment]
Hi @shaneing 

Can you give a little more context? It is not possible to find the problem just with the information that you provided.

Best regards

**Comment by shaneing** [comment]
@petroniocandido I'm so sorry. I have found that it's meaningless to get their values.
