### ISSUE TITLE
Defining the membership function

### ISSUE THREAD

**Issue by smejiame** [PYFTS/pyFTS#29]
Hello, 
I am performing a fuzzy time series analysis and I am trying to use grid partitioning with trapezoidal mf, however, when I ran:
fs = Grid.GridPartitioner(data = ts, npart = 20, mf = mf.trapmf)
I am still getting a triangle fuzzy set, how should I define the mf in the grid partitioning?

**Comment by smejiame** [comment]
Given the code here: https://github.com/PYFTS/pyFTS/blob/master/pyFTS/partitioners/Grid.py I also try with this:
fs = Grid.GridPartitioner(data = ts, npart = 20, membership_function = mf.trapmf)
Getting the same result of a fuzzy set with triangle mf.

**Comment by petroniocandido** [comment]
Hi @smejiame !

Sorry for the long delay. The correct parameter is 'func', as the the code below:
fs = Grid.GridPartitioner(data = ts, npart = 20, func = mf.trapmf)

Best regards
