### ISSUE TITLE
Error on plotting

### ISSUE THREAD

**Issue by jermaine1ronquillo** [PYFTS/pyFTS#7]
I use matplotlib for plotting, but somehow I get an error whenever I import pyFTS and plot just a simple graph (even though I'm not using pyFTS). Below is the error:
_UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans (prop.get_family(), self.defaultFamily[fontext]))_

I don't know what is happening,I already updated my fonts. And by checking the codes pyFTS also use matplotlib in the following format

_import matplotlib as plt
import matplotlib.pyplot as plt_

and some codes import matplotlib as

_import matplotlib.pylab as plt_

I'm using 
matplotlib 2.2.3
pyFTS 1.2.2
python 3.6.3
on Ubuntu

Regards

**Comment by petroniocandido** [comment]
Did you installed the pyFTS using pip? If yes, try to use the following command:

pip install -U git+https://github.com/PYFTS/pyFTS

**Comment by jermaine1ronquillo** [comment]
Thank you, it is now working
