### ISSUE TITLE
error on "Silva,_Sadaei,_Guimaraes_ProbabilisticWeightedFTS.ipynb" file

### ISSUE THREAD

**Issue by jermaine1ronquillo** [PYFTS/pyFTS#8]
I tried running the file under the section "Partitioning optimization" but I encountered an error.
Also I cannot read the file "pwfts_taiex_partitioning.csv".

**Comment by jermaine1ronquillo** [comment]
I also tried to run this command found in the notebook, 
_pfts1_taiex = pwfts.ProbabilisticWeightedFTS("1", partitioner=partitioner)_
It doesn't work, I have to delete "1" to make it work

**Comment by jermaine1ronquillo** [comment]
running this
_pfts1_taiex_diff.fit(dataset[:train_split], save_model=True, file_path='pwfts_diff')_
will result to _IndexError: list index out of range_

**Comment by petroniocandido** [comment]
This notebook is outdated and was even removed from the pyFTS repository! 

The developments about the PWFTS method now are on a separated repository and will be joined again on pyFTS after the PWFTS paper was published.

**Comment by jermaine1ronquillo** [comment]
That explains why,  the link is given on readme. It is a good example though.
